name: Build

on:
  push:
    tags:
    - v*

jobs:
  winbuild:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Setup environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: ThirdParty/SDL2*
        key: deps-sdl2-windows

    - name: Download dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      shell: cmd
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: call .\Scripts\WinDownloadDeps.bat
    
    - name: Build
      shell: cmd
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: call .\Scripts\WinBuild.bat
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Athena-Win-x64
        path: build/bin/Release/build
